name: 'Duplo Analyser'
description: '⚡️ Super fast duplicated blocks finder'
branding:
  icon: check-square
  color: green
inputs:
  directory:
    description: 'Top directory from which to search for files. Only used with include-pattern.'
    required: false
    default: '.'
  include-pattern:
    description: 'Regular expression used to include filenames for analysis (case-insensitive). Mutually exlusive with file-list.'
    required: false
  exclude-pattern:
    description: 'Regular expression used to exclude filenames for analysis (case-insensitive). Only used with include-pattern.'
    required: false
    default: '.^'
  file-list:
    description: 'File with filenames to analyse. Mutually exclusive with include-pattern.'
    required: false
    default: ''
  minimum-lines:
    description: 'Minimum number of lines required for duplicate detection'
    required: true
    default: "10"
  minimum-line-length:
   description: 'Minimum number of characters in line (lines with less are ignored)'
   required: true
   default: "3"
  max-files:
    description: 'Maximum number of files to report (useful if there are many duplicates)'
    required: true
    default: "100"
  ignore-preprocessor-directives:
    description: 'Remove pre-processor directives before doing duplicate detection'
    required: true
    default: "true"
  version:
    description: 'Version of Duplo to use'
    required: true
    default: 'v1.1.1'
runs:
  using: "composite"
  steps:

    # platform-specific setup

    - name: Set executable name
      shell: bash
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: echo "EXE=$RUNNER_TEMP/duplo" >> $GITHUB_ENV

    - name: Set executable name
      shell: bash
      if: runner.os == 'Windows'
      run: echo "EXE=$RUNNER_TEMP\duplo.exe" >> $GITHUB_ENV

    # rest is common

    - uses: actions/cache@v4
      id: cache
      with:
        path: ${{ env.EXE }}
        key: ${{ inputs.version }}

    - name: Set variables
      shell: bash
      run: |
        DUPLO=$(echo "duplo-$RUNNER_OS.zip" | tr '[:upper:]' '[:lower:]')
        echo "DUPLO=$DUPLO" >> "$GITHUB_ENV"
        echo "ARCHIVE=$RUNNER_TEMP/duplo.zip" >> "$GITHUB_ENV"

    - name: Download Duplo
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        # Fetch the releases JSON
        echo "Fetching releases from GitHub..."
        RELEASES_JSON=$(curl -s https://api.github.com/repos/dlidstrom/Duplo/releases)
        echo "Fetched JSON data."

        # Extract the correct release based on VERSION
        echo "Filtering release for version: $VERSION"
        RELEASE_JSON=$(echo "$RELEASES_JSON" | jq --arg tag "$VERSION" -r '.[] | select(.tag_name==$tag)')
        echo "Filtered Release JSON:"
        echo "$RELEASE_JSON"

        # Extract assets array
        echo "Extracting assets..."
        ASSETS_JSON=$(echo "$RELEASE_JSON" | jq -r '.assets')
        echo "Assets JSON:"
        echo "$ASSETS_JSON"

        # Find the correct asset by name
        echo "Searching for asset named: $DUPLO"
        DOWNLOAD_URL=$(echo "$ASSETS_JSON" | jq --arg name "$DUPLO" -r '.[] | select(.name==$name) | .browser_download_url')

        # Log the extracted download URL
        if [[ -n "$DOWNLOAD_URL" ]]; then
            echo "Found download URL: $DOWNLOAD_URL"
        else
            echo "Error: No matching asset found for $DUPLO"
            exit 1
        fi

        # Download the file
        echo "Downloading $DUPLO to $ARCHIVE..."
        curl -L -o "$ARCHIVE" "$DOWNLOAD_URL"
        echo "Download complete!"

        rm -f "$EXE"
        unzip "$ARCHIVE" -d "$RUNNER_TEMP"

    - name: Analyse files
      shell: bash
      run: |
        ARGS=(-ml "$INPUT_MINIMUM_LINES" -mc "$INPUT_MINIMUM_LINE_LENGTH")
        if [[ "$IGNORE_PREPROCESSOR_DIRECTIVES" =~ ^(true|True|1)$ ]]; then
          ARGS+=(-ip)
        fi

        if [[ -n "$FILE_LIST" ]]; then
          if [[ -n "$INCLUDE_PATTERN" ]]; then
            echo "INCLUDE_PATTERN and FILE_LIST are mutually exclusive; specify only one of them."
            exit 1
          fi

          if [[ -n "$EXCLUDE_PATTERN" ]]; then
            echo "warn: EXCLUDE_PATTERN is not used with FILE_LIST"
          fi

          if [[ -n "$DIRECTORY" ]]; then
            echo "warn: DIRECTORY is not used with FILE_LIST"
          fi

          ARGS+=("$FILE_LIST" -)
          echo "command: $EXE ${ARGS[*]}"
          "$EXE" "${ARGS[@]}"
        else
          INC=${INCLUDE_PATTERN:-.*}
          ARGS+=(- -)
          echo "command: $EXE ${ARGS[*]}"
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            find -E "$DIRECTORY" -type f \( -iregex "$INC" ! -iregex "$EXCLUDE_PATTERN" \) | "$EXE" "${ARGS[@]}"
          else
            find "$DIRECTORY" -type f \( -regextype posix-extended -iregex "$INC" ! -iregex "$EXCLUDE_PATTERN" \) | "$EXE" "${ARGS[@]}"
          fi
        fi
      env:
        INCLUDE_PATTERN: ${{ inputs.include-pattern }}
        EXCLUDE_PATTERN: ${{ inputs.exclude-pattern }}
        FILE_LIST: ${{ inputs.file-list }}
        INPUT_MINIMUM_LINES: ${{ inputs.minimum-lines }}
        INPUT_MINIMUM_LINE_LENGTH: ${{ inputs.minimum-line-length }}
        IGNORE_PREPROCESSOR_DIRECTIVES: ${{ inputs.ignore-preprocessor-directives }}
        DIRECTORY: ${{ inputs.directory }}
